import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowRightLeft, Boxes, Package, TrendingUp } from 'lucide-react';
import * as XLSX from 'xlsx';
import { useLocation, useNavigate } from 'react-router-dom';
import API_URL from '../../config/api';
import InventoryWorkflows, { PurchaseWorkflow } from './InventoryWorkflows';

const INVENTORY_SECTIONS = [
  { slug: '', label: 'Inventory Dashboard' },
  { slug: 'items', label: 'Inventory Items' },
  { slug: 'main-store', label: 'Main Store' },
  { slug: 'kitchen', label: 'Kitchen' },
  { slug: 'bar', label: 'Bar' },
  { slug: 'barista', label: 'Barista' },
  { slug: 'purchases', label: 'Purchases' },
  { slug: 'transfers', label: 'Transfers' },
  { slug: 'recipes', label: 'Recipes' },
  { slug: 'consumption', label: 'Consumption' },
  { slug: 'waste', label: 'Waste' },
  { slug: 'stock-counts', label: 'Stock Counts' },
  { slug: 'adjustments', label: 'Adjustments' },
  { slug: 'valuation', label: 'Valuation' },
  { slug: 'reports', label: 'Inventory Reports' },
];

function currency(value) {
  const number = Number(value || 0);
  return new Intl.NumberFormat('en-UG', {
    style: 'currency',
    currency: 'UGX',
    maximumFractionDigits: 0,
  }).format(number);
}
function sessionHeaders() {
  try {
    const session = JSON.parse(localStorage.getItem('kurax_user') || '{}');
    return session.token ? { Authorization: `Bearer ${session.token}` } : {};
  } catch {
    return {};
  }
}

function downloadInventorySummaryExcel(report, businessDate) {
  const workbook = XLSX.utils.book_new();
  const summaryRows = [
    ['Kurax Food Lounge & Bistro'],
    ['Inventory Summary Report'],
    ['Business Date', report.businessDate || businessDate],
    ['Reporting Period', report.period || 'Daily'],
    ['Department', report.departmentLabel || 'All Main Departments'],
    ['Generated By', report.generatedBy || 'Accountant'],
    [],
    ['Metric', 'Value (UGX)'],
    ['Opening Inventory Value', report.summary?.openingInventoryValue || 0],
    ['Purchases Received', report.summary?.purchasesReceived || 0],
    ['Consumption Value', report.summary?.consumptionValue || 0],
    ['Waste Value', report.summary?.wasteValue || 0],
    ['Closing Inventory Value', report.summary?.closingInventoryValue || 0],
    ['Total Items', report.summary?.totalItems || 0],
    ['Low Stock Items', report.summary?.lowStockCount || 0],
    ['Out of Stock Items', report.summary?.outOfStockCount || 0],
  ];
  XLSX.utils.book_append_sheet(workbook, XLSX.utils.aoa_to_sheet(summaryRows), 'Summary');

  const departmentRows = Object.entries(report.departmentBreakdown || {}).map(([department, values]) => ({
    Department: department,
    ...values,
  }));
  XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(departmentRows), 'Departments');
  XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(report.itemRows || []), 'Inventory Items');
  XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(report.alerts || []), 'Stock Alerts');
  XLSX.writeFile(workbook, `Kurax_Inventory_Summary_${businessDate || report.businessDate}.xlsx`);
}

export default function InventoryManagement() {
  const location = useLocation();
  const navigate = useNavigate();
  const selectedSlug = location.pathname.replace('/accountant/inventory', '').split('/').filter(Boolean)[0] || '';
  const currentSection = INVENTORY_SECTIONS.find((section) => section.slug === selectedSlug) || INVENTORY_SECTIONS[0];
  const [stats, setStats] = useState({
    total_inventory_value: 0,
    total_items: 0,
    low_stock_items: 0,
    out_of_stock_items: 0,
    total_purchases: 0,
    total_consumption: 0,
    total_waste: 0,
  });
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [locations, setLocations] = useState([]);
  const [relatedData, setRelatedData] = useState({});
  const [actionMessage, setActionMessage] = useState('');
  const [actionError, setActionError] = useState('');
  const [reportFilters, setReportFilters] = useState({
    period: 'Daily',
    businessDate: '2026-10-10',
    startDate: '2026-10-10',
    endDate: '2026-10-10',
    department: 'ALL',
    reportType: 'Inventory Summary',
    exportFormat: 'PDF',
  });
  const [reportPreview, setReportPreview] = useState(null);
  const [reportLoading, setReportLoading] = useState(false);
  const [reportError, setReportError] = useState('');
  const [reportMessage, setReportMessage] = useState('');

  const loadData = async () => {
    setLoading(true);
    try {
      const [dashboardRes, itemsRes, locationsRes] = await Promise.all([
        fetch(`${API_URL}/api/inventory/dashboard`),
        fetch(`${API_URL}/api/inventory/items`),
        fetch(`${API_URL}/api/inventory/locations`),
      ]);

      const dashboard = dashboardRes.ok ? await dashboardRes.json() : {};
      const collectedItems = itemsRes.ok ? await itemsRes.json() : [];
      const collectedLocations = locationsRes.ok ? await locationsRes.json() : [];

      setStats({
        total_inventory_value: Number(dashboard.total_inventory_value || 0),
        total_items: Number(dashboard.total_items || 0),
        low_stock_items: Number(dashboard.low_stock_items || 0),
        out_of_stock_items: Number(dashboard.out_of_stock_items || 0),
        total_purchases: Number(dashboard.total_purchases || 0),
        total_consumption: Number(dashboard.total_consumption || 0),
        total_waste: Number(dashboard.total_waste || 0),
      });
      setItems(collectedItems);
      setLocations(collectedLocations);
    } catch (error) {
      console.error('Inventory dashboard load failed:', error);
    } finally {
      setLoading(false);
    }
  };

  const loadRelatedData = async () => {
    const endpointsBySection = {
      purchases: ['purchases'],
      transfers: ['transfers'],
      recipes: ['recipes'],
      consumption: ['consumption'],
      waste: ['waste'],
      'stock-counts': ['stock-counts'],
      adjustments: ['adjustments'],
      reports: ['reports/low-stock', 'reports/menu-items-without-recipes', 'transactions'],
    };
    const endpoints = endpointsBySection[currentSection.slug] || [];
    const entries = await Promise.all(endpoints.map(async (endpoint) => {
      try {
        const response = await fetch(`${API_URL}/api/inventory/${endpoint}`, { headers: sessionHeaders() });
        if (!response.ok) throw new Error(`Unable to load ${endpoint}.`);
        return [endpoint, await response.json()];
      } catch (error) {
        console.error(`Inventory ${endpoint} history load failed:`, error);
        return [endpoint, []];
      }
    }));
    setRelatedData(Object.fromEntries(entries));
  };

  const runInventoryAction = async (path, payload, method, successMessage) => {
    setActionMessage('');
    setActionError('');
    try {
      const response = await fetch(`${API_URL}/api/inventory/${path}`, {
        method: method || 'POST',
        headers: { ...sessionHeaders(), 'Content-Type': 'application/json' },
        ...(method === 'GET' ? {} : { body: JSON.stringify(payload || {}) }),
      });
      const result = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(result.error || 'Inventory request failed.');
      setActionMessage(successMessage || 'Inventory updated.');
      await Promise.all([loadData(), loadRelatedData()]);
      return result;
    } catch (error) {
      setActionError(error.message || 'Inventory request failed.');
      return null;
    }
  };

  const updateReportFilters = (field, value) => {
    setReportFilters((previous) => ({ ...previous, [field]: value }));
  };

  const applyPeriodDefaults = (period) => {
    const businessDate = reportFilters.businessDate || '2026-10-10';
    if (period === 'Daily') {
      setReportFilters((previous) => ({ ...previous, period, startDate: businessDate, endDate: businessDate }));
      return;
    }
    if (period === 'Weekly' || period === 'Monthly') {
      setReportFilters((previous) => ({ ...previous, period, startDate: businessDate, endDate: businessDate }));
      return;
    }
    setReportFilters((previous) => ({ ...previous, period, startDate: previous.startDate || businessDate, endDate: previous.endDate || businessDate }));
  };

  const fetchInventorySummary = async (exportFormat = 'json', shouldDownload = false) => {
    setReportError('');
    setReportLoading(true);
    try {
      const normalizedFormat = String(exportFormat).toLowerCase();
      const requestFormat = normalizedFormat === 'xlsx' ? 'json' : normalizedFormat;
      const response = await fetch(`${API_URL}/api/inventory/reports/summary`, {
        method: 'POST',
        headers: { ...sessionHeaders(), 'Content-Type': 'application/json' },
        body: JSON.stringify({
          business_date: reportFilters.businessDate,
          start_date: reportFilters.startDate,
          end_date: reportFilters.endDate,
          department: reportFilters.department,
          period: reportFilters.period,
          report_type: reportFilters.reportType,
          export_format: requestFormat,
        }),
      });

      if (shouldDownload && normalizedFormat === 'pdf') {
        if (!response.ok) {
          const errorPayload = await response.json().catch(() => ({}));
          throw new Error(errorPayload.error || 'Unable to generate inventory summary PDF.');
        }
        const blob = await response.blob();
        const fileUrl = URL.createObjectURL(blob);
        const anchor = document.createElement('a');
        anchor.href = fileUrl;
        anchor.download = `Kurax_Inventory_Summary_${reportFilters.businessDate || reportFilters.startDate}.pdf`;
        anchor.click();
        URL.revokeObjectURL(fileUrl);
        setReportMessage('Inventory summary PDF download started successfully.');
        setReportPreview(null);
        return;
      }

      const payload = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(payload.error || 'Unable to preview inventory summary.');
      if (shouldDownload && normalizedFormat === 'xlsx') {
        downloadInventorySummaryExcel(payload, reportFilters.businessDate || reportFilters.startDate);
        setReportMessage('Inventory summary Excel workbook download started successfully.');
        setReportPreview(null);
        return;
      }
      setReportPreview(payload);
      setReportMessage('Report preview refreshed successfully.');
    } catch (error) {
      setReportError(error.message || 'Unable to generate inventory summary.');
    } finally {
      setReportLoading(false);
    }
  };

  useEffect(() => {
    loadData();
    loadRelatedData();
  }, [currentSection.slug]);

  const lowStockItems = useMemo(
    () => items.filter((item) => String(item.stock_status || '').includes('LOW') || Number(item.current_quantity || 0) <= Number(item.minimum_stock_level || 0)),
    [items]
  );
  const visibleItems = useMemo(() => {
    if (currentSection.slug === 'main-store') return items.filter((item) => String(item.location_name || '').toLowerCase() === 'main store');
    if (['kitchen', 'bar', 'barista'].includes(currentSection.slug)) return items.filter((item) => String(item.station || '').toLowerCase() === currentSection.slug);
    if (currentSection.slug === 'reports') return lowStockItems;
    return items;
  }, [currentSection.slug, items, lowStockItems]);
  const isStockSection = ['', 'items', 'main-store', 'kitchen', 'bar', 'barista', 'valuation'].includes(currentSection.slug);
  const showPurchaseForm = currentSection.slug === '';
  const workflowSections = ['purchases', 'transfers', 'recipes', 'consumption', 'waste', 'stock-counts', 'adjustments', 'reports'];

  return (
    <div className="bg-[#f5f3ee] p-5 text-zinc-900">
      <div className="mx-auto max-w-7xl">
        <div className="mb-6 flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
          <div>
            <p className="text-[10px] font-black uppercase tracking-[0.3em] text-yellow-600">Accountant</p>
            <h1 className="mt-2 text-3xl font-black uppercase italic tracking-tight">{currentSection.label}</h1>
          </div>
          <button
            type="button"
            onClick={loadData}
            className="rounded-xl border border-zinc-300 bg-white px-4 py-2 text-xs font-black uppercase tracking-widest text-zinc-800 shadow-sm"
          >
            Refresh Data
          </button>
        </div>

        <nav aria-label="Inventory sections" className="mb-6 flex gap-2 overflow-x-auto border-b border-zinc-200 pb-3">
          {INVENTORY_SECTIONS.map((section) => {
            const isActive = section.slug === currentSection.slug;
            return (
              <button
                key={section.slug || 'dashboard'}
                type="button"
                aria-current={isActive ? 'page' : undefined}
                onClick={() => navigate(section.slug ? `/accountant/inventory/${section.slug}` : '/accountant/inventory')}
                className={`shrink-0 rounded-lg px-3 py-2 text-xs font-bold transition-colors ${isActive ? 'bg-zinc-900 text-white' : 'bg-white text-zinc-600 hover:bg-zinc-100'}`}
              >
                {section.label}
              </button>
            );
          })}
        </nav>

        {['', 'valuation'].includes(currentSection.slug) && <div className="mb-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
          <StatCard icon={<Boxes size={18} />} label="Inventory Value" value={currency(stats.total_inventory_value)} accent="amber" />
          <StatCard icon={<Package size={18} />} label="Items" value={String(stats.total_items)} accent="slate" />
          <StatCard icon={<AlertTriangle size={18} />} label="Low Stock" value={String(stats.low_stock_items)} accent="rose" />
          <StatCard icon={<TrendingUp size={18} />} label="Purchases" value={currency(stats.total_purchases)} accent="emerald" />
        </div>}

        {actionError && <p role="alert" className="mb-4 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-800">{actionError}</p>}
        {actionMessage && <p role="status" className="mb-4 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{actionMessage}</p>}

        {currentSection.slug === 'reports' ? (
          <div className="space-y-6">
            <div className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm">
              <div className="mb-5 flex items-center justify-between gap-3">
                <div>
                  <p className="text-[10px] font-black uppercase tracking-[0.2em] text-amber-700">Inventory Reports & Downloads</p>
                  <h2 className="mt-2 text-xl font-black uppercase tracking-tight text-zinc-900">Inventory Summary</h2>
                </div>
                <div className="rounded-full bg-amber-100 px-2 py-1 text-[9px] font-black uppercase tracking-[0.2em] text-amber-700">Daily · 2026-10-10</div>
              </div>

              <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
                <label className="space-y-2 text-xs font-bold uppercase tracking-[0.15em] text-zinc-600">
                  <span>Reporting Period</span>
                  <select value={reportFilters.period} onChange={(event) => applyPeriodDefaults(event.target.value)} className="w-full rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2 text-sm font-semibold text-zinc-900 outline-none focus:border-amber-500">
                    <option value="Daily">Daily</option>
                    <option value="Weekly">Weekly</option>
                    <option value="Monthly">Monthly</option>
                    <option value="Custom">Custom Date Range</option>
                  </select>
                </label>

                <label className="space-y-2 text-xs font-bold uppercase tracking-[0.15em] text-zinc-600">
                  <span>Business Date</span>
                  <input type="date" value={reportFilters.businessDate} onChange={(event) => updateReportFilters('businessDate', event.target.value)} className="w-full rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2 text-sm font-semibold text-zinc-900 outline-none focus:border-amber-500" />
                </label>

                <label className="space-y-2 text-xs font-bold uppercase tracking-[0.15em] text-zinc-600">
                  <span>Start Date</span>
                  <input type="date" value={reportFilters.startDate} onChange={(event) => updateReportFilters('startDate', event.target.value)} className="w-full rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2 text-sm font-semibold text-zinc-900 outline-none focus:border-amber-500" />
                </label>

                <label className="space-y-2 text-xs font-bold uppercase tracking-[0.15em] text-zinc-600">
                  <span>End Date</span>
                  <input type="date" value={reportFilters.endDate} onChange={(event) => updateReportFilters('endDate', event.target.value)} className="w-full rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2 text-sm font-semibold text-zinc-900 outline-none focus:border-amber-500" />
                </label>

                <label className="space-y-2 text-xs font-bold uppercase tracking-[0.15em] text-zinc-600">
                  <span>Department</span>
                  <select value={reportFilters.department} onChange={(event) => updateReportFilters('department', event.target.value)} className="w-full rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2 text-sm font-semibold text-zinc-900 outline-none focus:border-amber-500">
                    <option value="ALL">All Main Departments</option>
                    <option value="MAIN STORE">Main Store</option>
                    <option value="KITCHEN">Kitchen</option>
                    <option value="BAR">Bar</option>
                    <option value="BARISTA">Barista</option>
                  </select>
                </label>

                <label className="space-y-2 text-xs font-bold uppercase tracking-[0.15em] text-zinc-600">
                  <span>Report Type</span>
                  <select value={reportFilters.reportType} onChange={(event) => updateReportFilters('reportType', event.target.value)} className="w-full rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2 text-sm font-semibold text-zinc-900 outline-none focus:border-amber-500">
                    <option value="Inventory Summary">Inventory Summary</option>
                    <option value="Purchases and Suppliers">Purchases and Suppliers</option>
                    <option value="Stock Consumption and COGS">Stock Consumption and COGS</option>
                  </select>
                </label>

                <label className="space-y-2 text-xs font-bold uppercase tracking-[0.15em] text-zinc-600">
                  <span>Export Format</span>
                  <select value={reportFilters.exportFormat} onChange={(event) => updateReportFilters('exportFormat', event.target.value)} className="w-full rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2 text-sm font-semibold text-zinc-900 outline-none focus:border-amber-500">
                    <option value="PDF">PDF</option>
                    <option value="XLSX">Excel (.xlsx)</option>
                  </select>
                </label>

                <div className="space-y-2 text-xs font-bold uppercase tracking-[0.15em] text-zinc-600">
                  <span>Actions</span>
                  <div className="flex flex-wrap gap-2">
                    <button type="button" onClick={() => fetchInventorySummary('json')} disabled={reportLoading} className="rounded-xl bg-zinc-900 px-3 py-2 text-[10px] font-black uppercase tracking-[0.2em] text-white disabled:cursor-not-allowed disabled:opacity-50">
                      {reportLoading ? 'Loading...' : 'Preview Report'}
                    </button>
                    <button type="button" onClick={() => fetchInventorySummary(reportFilters.exportFormat.toLowerCase(), true)} disabled={reportLoading} className="rounded-xl bg-amber-400 px-3 py-2 text-[10px] font-black uppercase tracking-[0.2em] text-zinc-900 disabled:cursor-not-allowed disabled:opacity-50">
                      {reportLoading ? 'Generating...' : `Download ${reportFilters.exportFormat === 'XLSX' ? 'Excel' : 'PDF'}`}
                    </button>
                  </div>
                </div>
              </div>

              {reportError && <p role="alert" className="mt-4 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-800">{reportError}</p>}
              {reportMessage && <p role="status" className="mt-4 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{reportMessage}</p>}
            </div>

            {reportPreview && (
              <div className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm">
                <h3 className="mb-4 text-lg font-black uppercase tracking-tight text-zinc-900">Executive Summary</h3>
                <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
                  <SummaryRow label="Opening Inventory Value" value={currency(reportPreview.summary?.openingInventoryValue || 0)} />
                  <SummaryRow label="Purchases Received" value={currency(reportPreview.summary?.purchasesReceived || 0)} />
                  <SummaryRow label="Consumption Value" value={currency(reportPreview.summary?.consumptionValue || 0)} />
                  <SummaryRow label="Closing Inventory Value" value={currency(reportPreview.summary?.closingInventoryValue || 0)} />
                </div>
                <div className="mt-4 overflow-x-auto">
                  <table className="min-w-full text-left text-xs">
                    <thead className="bg-zinc-100">
                      <tr>
                        <th className="px-3 py-2 font-black uppercase tracking-wide text-zinc-700">Department</th>
                        <th className="px-3 py-2 font-black uppercase tracking-wide text-zinc-700">Items</th>
                        <th className="px-3 py-2 font-black uppercase tracking-wide text-zinc-700">Closing Value</th>
                        <th className="px-3 py-2 font-black uppercase tracking-wide text-zinc-700">Low Stock</th>
                        <th className="px-3 py-2 font-black uppercase tracking-wide text-zinc-700">Out of Stock</th>
                      </tr>
                    </thead>
                    <tbody>
                      {Object.entries(reportPreview.departmentBreakdown || {}).map(([name, value]) => (
                        <tr key={name} className="border-b border-zinc-100">
                          <td className="px-3 py-3 font-semibold text-zinc-800">{name}</td>
                          <td className="px-3 py-3 text-zinc-700">{value.itemCount || 0}</td>
                          <td className="px-3 py-3 text-zinc-700">{currency(value.closingInventoryValue || 0)}</td>
                          <td className="px-3 py-3 text-zinc-700">{value.lowStockItems || 0}</td>
                          <td className="px-3 py-3 text-zinc-700">{value.outOfStockItems || 0}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </div>
        ) : workflowSections.includes(currentSection.slug) ? (
          <InventoryWorkflows
            section={currentSection.slug}
            items={items}
            locations={locations}
            records={relatedData}
            onAction={runInventoryAction}
            readOnly={['recipes', 'consumption', 'waste'].includes(currentSection.slug)}
          />
        ) : (
        <div className="space-y-6">
          {isStockSection && <>
          <div className="rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm">
            <div className="mb-4 flex items-center justify-between">
              <h2 className="text-lg font-black uppercase tracking-tight">Inventory Stock</h2>
              <span className="rounded-full bg-zinc-100 px-2 py-1 text-[9px] font-black uppercase tracking-[0.2em] text-zinc-600">
                {visibleItems.length} items
              </span>
            </div>

            <div className="overflow-x-auto">
              <table className="min-w-full text-left text-xs">
                <thead className="bg-zinc-100 text-zinc-700">
                  <tr>
                    <th className="px-3 py-2 font-black uppercase tracking-wide">Item</th>
                    <th className="px-3 py-2 font-black uppercase tracking-wide">Qty</th>
                    <th className="px-3 py-2 font-black uppercase tracking-wide">Unit</th>
                    <th className="px-3 py-2 font-black uppercase tracking-wide">Value</th>
                    <th className="px-3 py-2 font-black uppercase tracking-wide">Status</th>
                  </tr>
                </thead>
                <tbody>
                  {loading ? (
                    <tr>
                      <td colSpan={5} className="px-3 py-6 text-center text-zinc-500">Loading inventory…</td>
                    </tr>
                  ) : visibleItems.length === 0 ? (
                    <tr>
                      <td colSpan={5} className="px-3 py-6 text-center text-zinc-500">No inventory items found.</td>
                    </tr>
                  ) : (
                    visibleItems.map((item) => (
                      <tr key={item.id} className="border-b border-zinc-100 align-top">
                        <td className="px-3 py-3">
                          <div className="font-bold text-zinc-800">{item.item_name}</div>
                          <div className="text-[10px] text-zinc-500">{item.location_name || 'Main Store'} · {item.station || 'KITCHEN'}</div>
                        </td>
                        <td className="px-3 py-3 font-semibold text-zinc-700">{Number(item.current_quantity || 0)} {item.unit || 'kg'}</td>
                        <td className="px-3 py-3 text-zinc-600">{item.unit || 'kg'}</td>
                        <td className="px-3 py-3 font-bold text-zinc-800">{currency(item.inventory_value || 0)}</td>
                        <td className="px-3 py-3">
                          <span className={`rounded-full px-2 py-1 text-[9px] font-black uppercase tracking-widest ${
                            item.stock_status === 'OUT OF STOCK' ? 'bg-rose-100 text-rose-700' : item.stock_status === 'LOW STOCK' ? 'bg-amber-100 text-amber-700' : 'bg-emerald-100 text-emerald-700'
                          }`}>
                            {item.stock_status || 'IN STOCK'}
                          </span>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>
          </>}

          {showPurchaseForm && <>
          <div className="space-y-6">
            <PurchaseWorkflow locations={locations} onAction={runInventoryAction} showHistory={false} />
            <div className="rounded-2xl border border-dashed border-zinc-300 bg-zinc-50 p-4">
              <div className="mb-3 flex items-center gap-2 text-zinc-700">
                <ArrowRightLeft size={16} />
                <p className="text-[10px] font-black uppercase tracking-[0.2em]">Operational summary</p>
              </div>
              <div className="space-y-2 text-xs">
                <SummaryRow label="Low stock items" value={String(lowStockItems.length)} />
                <SummaryRow label="Out of stock" value={String(stats.out_of_stock_items)} />
                <SummaryRow label="Consumption" value={currency(stats.total_consumption)} />
                <SummaryRow label="Waste" value={currency(stats.total_waste)} />
              </div>
            </div>
          </div>
          </>}

        </div>
        )}
      </div>
    </div>
  );
}

function StatCard({ icon, label, value, accent }) {
  const colors = {
    amber: 'bg-amber-100 text-amber-700',
    slate: 'bg-slate-100 text-slate-700',
    rose: 'bg-rose-100 text-rose-700',
    emerald: 'bg-emerald-100 text-emerald-700',
  };

  return (
    <div className="rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm">
      <div className="flex items-center justify-between gap-3">
        <div>
          <p className="text-[10px] font-black uppercase tracking-[0.2em] text-zinc-500">{label}</p>
          <p className="mt-2 text-2xl font-black tracking-tight text-zinc-900">{value}</p>
        </div>
        <div className={`rounded-xl p-2 ${colors[accent] || colors.amber}`}>{icon}</div>
      </div>
    </div>
  );
}

function SummaryRow({ label, value }) {
  return (
    <div className="flex items-center justify-between rounded-lg bg-white px-2 py-2 text-zinc-700">
      <span>{label}</span>
      <span className="font-bold text-zinc-900">{value}</span>
    </div>
  );
}

